{"name": "Авторизация с неверным паролем", "status": "passed", "description": "Проверка, что система возвращает ошибку при неверном пароле", "steps": [{"name": "Попытка авторизации с логином: ythvsoeuzv, неверным паролем и именем: onmxnfsqiq", "status": "passed", "start": 1727644469798, "stop": 1727644470048}, {"name": "Проверка ошибки при неверном пароле", "status": "passed", "start": 1727644470048, "stop": 1727644470048}], "start": 1727644469798, "stop": 1727644470049, "uuid": "56d658cf-5215-454d-840b-0e7f091d8cc5", "historyId": "2a00be006f37724aa6b6de913343aa60", "testCaseId": "2a00be006f37724aa6b6de913343aa60", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_with_invalid_password", "labels": [{"name": "suite", "value": "Тесты логина курьера"}, {"name": "tag", "value": "@pytest.mark.usefixtures('courier_data')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-N041KP4"}, {"name": "thread", "value": "2608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}